// LogisticsManager.idl : LogisticsManager.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(LogisticsManager.tlb)。

#include "olectl.h"
[uuid(A7C7F7B4-EE61-463F-9AF7-230229C30295), version(1.0)]
library LogisticsManager
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CLogisticsManagerDoc 的主调度接口
	
	[ uuid(32B476DB-609D-41C0-AE45-83BBCCADC14D) ]
	dispinterface ILogisticsManager
	{
		properties:
			
		methods:
	};

	//  CLogisticsManagerDoc 的类信息
	
	[ uuid(7FF20474-B532-4E97-B339-4A7B356D1336) ]
	coclass LogisticsManager
	{
		[default] dispinterface ILogisticsManager;
	};
	//  Primary dispatch interface for UserLoginPage
		
	[ uuid(571160B3-5F1E-437E-AB49-259A8F4E7AC9) ]
	dispinterface IUserLoginPage
	{
		properties:
		methods:
	};

	//  Class information for UserLoginPage

	[ uuid(25ADB8AF-6A60-4A45-8D8A-5E56A2F1A660) ]
	coclass UserLoginPage
	{
		[default] dispinterface IUserLoginPage;
	};
	
	//  Primary dispatch interface for CAddOrderPage
		
	[ uuid(4852161E-BE95-4EEE-B991-5ED0BFDD926F) ]
	dispinterface IAddOrderPage
	{
		properties:
		methods:
	};

	//  Class information for CAddOrderPage

	[ uuid(73E5533B-E650-4B2C-B47B-6A519418A3D5) ]
	coclass CAddOrderPage
	{
		[default] dispinterface IAddOrderPage;
	};
};
